// Code generated by MockGen. DO NOT EDIT.
// Source: repository/estate/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=repository/estate/interfaces.go -destination=repository/estate/interfaces.mock.gen.go -package=estate
//

// Package estate is a generated GoMock package.
package estate
