// Code generated by MockGen. DO NOT EDIT.
// Source: service/estate/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=service/estate/interfaces.go -destination=service/estate/interfaces.mock.gen.go -package=estate
//

// Package estate is a generated GoMock package.
package estate

import (
	context "context"
	reflect "reflect"

	estate "github.com/SawitProRecruitment/UserService/repository/estate"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateNewEstate mocks base method.
func (m *MockService) CreateNewEstate(ctx context.Context, width, length int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewEstate", ctx, width, length)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNewEstate indicates an expected call of CreateNewEstate.
func (mr *MockServiceMockRecorder) CreateNewEstate(ctx, width, length any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewEstate", reflect.TypeOf((*MockService)(nil).CreateNewEstate), ctx, width, length)
}

// RetrieveEstate mocks base method.
func (m *MockService) RetrieveEstate(ctx context.Context, id string) (*estate.Estate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveEstate", ctx, id)
	ret0, _ := ret[0].(*estate.Estate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveEstate indicates an expected call of RetrieveEstate.
func (mr *MockServiceMockRecorder) RetrieveEstate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveEstate", reflect.TypeOf((*MockService)(nil).RetrieveEstate), ctx, id)
}
